- name: variable
  hosts: localhost
  become: yes
  vars:
    trainer: "mani"
    course: "devops"
  tasks:
  - name: variables 
    ansible.builtin.debug:
      msg: "hi this is mani learning {{course}} trainer is {{trainer}}