- name: variables with prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: pls enter ur USERNAME
    private: false
    prompt: pls enter ur password
    private: true
  tasks:
  - name: print and check variables 
    ansible.builtin.debug:
      msg: "username is: {{USERNAME}}, password is: {{password}}"
 