- name: variables with prompt
  hosts: localhost
  become: yes
  vars_prompt:
  - name: USERNAME
    prompt: pls enter ur username
    private: false
  - name: PASSWORD
    prompt: pls enter ur password
    private: true
  tasks:
  - name: print and check values 
    anisible.builtin.debug:
      msg: "username is {{USERNAME}}, password is {{PASSWORD}}"