- name: creating ec2 instance
  hosts: web
  become: yes
  tasks:
  - name: install apache package
    ansinle.builtin.package:
      name: apache
      state: present
  - name: run apache
    ansible.builtin.service:
      name: apache
      state: started