- name: creating ec2 instance
  hosts: web
  become: yes
  tasks:
  - name: install apache httpd
    ansinle.builtin.apt:
      name: apache 2
      state: present
  - name: run apache
    ansible.builtin.service:
      name: apache 2
      state: started