- name: creating ec2 instance
  hosts: localhost
  become: yes
  tasks:
  - name: install apache httpd
    ansinle.buitin.package:
      name: apache
      state: present
  - name: run apache
    ansible.builtin.service:
      name: apache
      state: started